name: Netlify Deploy

on:
  pull_request:
    branches:
      - main # 프로덕션 배포
      - develop # 테스트 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          URL=$(netlify deploy --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID --message "Develop branch deploy for testing" --json | jq -r .deploy_url)
          echo "Deploy URL: $URL"
          echo "TEST_DEPLOY_URL=$URL" >> $GITHUB_ENV
