name: Deploy Preview for PRs

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. AWS 인증 정보 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3. 의존성 설치
      - name: Install dependencies
        run: yarn install

      # 4. 빌드 실행
      - name: Build application
        run: yarn build

      # 5. S3에 미리보기 배포
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://davinci-preview-bucket/pr-${{ github.event.number }} --delete

      # 6. PR에 미리보기 URL 등록
      - name: Add Preview URL to PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Preview available at: https://davinci-preview-bucket.s3.amazonaws.com/pr-${{ github.event.number }}/"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
