name: Restrict direct pushes

on:
  push:
    branches:
      - main
      - develop

jobs:
  block_direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if direct push
        run: |
          echo "❌ Direct push to 'main' or 'develop' branch is not allowed. Please use a pull request."
          exit 1
